// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPSrHKSz-3trgEZ---OobCdSLKFimbK-4',
    appId: '1:934051412849:web:f77fc29d39ddf3cff214d0',
    messagingSenderId: '934051412849',
    projectId: 'nearshare-149f6',
    authDomain: 'nearshare-149f6.firebaseapp.com',
    storageBucket: 'nearshare-149f6.firebasestorage.app',
    measurementId: 'G-YLYJK483WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKYDuzWNao_coRjxv89s8avaerNxDvj8M',
    appId: '1:934051412849:android:e6f30d11015c4774f214d0',
    messagingSenderId: '934051412849',
    projectId: 'nearshare-149f6',
    storageBucket: 'nearshare-149f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm03yikQJ3kS7OaBf4IFkRGbFma37ZU8A',
    appId: '1:934051412849:ios:751d8d1c02dc12c7f214d0',
    messagingSenderId: '934051412849',
    projectId: 'nearshare-149f6',
    storageBucket: 'nearshare-149f6.firebasestorage.app',
    iosBundleId: 'com.example.nearShare',
  );
}
